services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: konil
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    # If you prefer, you can mount your source to pick up live code changes:
    # volumes:
    #   - .:/app
    # command: >
    #   sh -c "alembic upgrade head &&
    #          uvicorn main:app --reload --host 0.0.0.0 --port 8000"

volumes:
  db_data:
